name: alarme_feriados
description: Alarme para feriados brasileiros.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  drift: ^2.20.0
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.0
  path: ^1.9.1
  alarm: ^4.0.0
  permission_handler: ^11.3.0
  workmanager: ^0.5.0
  geolocator: ^13.0.0
  geocoding: ^3.0.0
  http: ^1.2.0
  shared_preferences: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  drift_dev: ^2.20.0
  build_runner: ^2.4.0
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: launcher_icon
  ios: true
  image_path: assets/icon/icon.png
  adaptive_icon_background: '#FF6B00'
  adaptive_icon_foreground: assets/icon/icon_foreground.png
  min_sdk_android: 21
  web:
    generate: false
  macos:
    generate: false

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
